export enum ERROR_CODES {
  COMPANY_RELATIONSHIP_ALREADY_EXISTS,
  COMPANY_RELATIONSHIP_DOES_NOT_EXIST,
  USER_ROLE_ALREADY_EXISTS,
  USER_ROLE_DOES_NOT_EXIST,
  COMPANY_ID_REQUIRED,
  COMPANY_ALREADY_EXISTS,
  INVALID_REQUEST,
  USER_ALREADY_EXISTS,
  TAG_CATEGORY_ALREADY_EXISTS,
  TAG_CATEGORY_NOT_FOUND,
  WAREHOUSE_NOT_FOUND,
  COMPANY_NOT_FOUND,
  FIELD_NOT_FOUND,
  FIELD_ALREADY_EXISTS,
  API_NOT_IMPLEMENTED,
  TAG_NOT_FOUND,
  INVALID_BILLING_SPLIT_GROUP,
  STORAGE_LOCATION_NOT_FOUND,
}

export const ERROR_MESSAGES: Record<ERROR_CODES, string> = {
  [ERROR_CODES.COMPANY_RELATIONSHIP_ALREADY_EXISTS]:
    'Relationship already exists.',
  [ERROR_CODES.COMPANY_RELATIONSHIP_DOES_NOT_EXIST]:
    'Relationship does not exist.',
  [ERROR_CODES.USER_ROLE_ALREADY_EXISTS]: 'User already has this role.',
  [ERROR_CODES.USER_ROLE_DOES_NOT_EXIST]: 'User role does not exist.',
  [ERROR_CODES.COMPANY_ID_REQUIRED]: 'Company ID is required.',
  [ERROR_CODES.COMPANY_ALREADY_EXISTS]: 'Company already exists.',
  [ERROR_CODES.WAREHOUSE_NOT_FOUND]: 'Warehouse not found.',
  [ERROR_CODES.COMPANY_NOT_FOUND]: 'Company not found.',
  [ERROR_CODES.INVALID_REQUEST]: 'Invalid request.',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists.',
  [ERROR_CODES.TAG_CATEGORY_ALREADY_EXISTS]: 'Tag category already exists.',
  [ERROR_CODES.TAG_CATEGORY_NOT_FOUND]: 'Tag category not found.',
  [ERROR_CODES.FIELD_NOT_FOUND]: 'Field not found.',
  [ERROR_CODES.FIELD_ALREADY_EXISTS]: 'Field already exists.',
  [ERROR_CODES.API_NOT_IMPLEMENTED]: 'API not implemented.',
  [ERROR_CODES.TAG_NOT_FOUND]: 'Tag not found.',
  [ERROR_CODES.INVALID_BILLING_SPLIT_GROUP]:
    'Invalid billing split group. Please check your input and try again.',
  [ERROR_CODES.STORAGE_LOCATION_NOT_FOUND]: 'Storage location not found.',
}
